from Selection.double_selection import DoubleSelection
from Selection.select_all import SelectAll
from Selection.elite import Elite
from Selection.ranking import Ranking
from Selection.boltzmann import Boltzmann
from Selection.d_tournament import DeterministicTournament
from Selection.p_tournament import ProbabilisticTournament
from Selection.roulette import Roulette
from Selection.universal import Universal
